steps:
  - name: 'gcr.io/cloud-builders/go'
    env: ['GO111MODULE=on', 'PROJECT_ROOT=sutaba-server']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get install build-essential && make lint
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/go'
    env: ['GO111MODULE=on', 'PROJECT_ROOT=sutaba-server']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get install build-essential && make test
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-pull'
    entrypoint: 'bash'
    waitFor: ['-']
    args:
      - '-c'
      - |
        docker pull asia.gcr.io/$PROJECT_ID/sutaba-server:master || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['docker-pull']
    args: [ 'build',
            '-t', 'asia.gcr.io/$PROJECT_ID/sutaba-server', '.',
            '--cache-from', 'asia.gcr.io/$PROJECT_ID/sutaba-server:$BRANCH_NAME',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/sutaba-server:$BRANCH_NAME']
