steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull asia.gcr.io/$PROJECT_ID/sutaba-server:master || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'asia.gcr.io/$PROJECT_ID/sutaba-server', '.',
            '--cache-from', 'asia.gcr.io/$PROJECT_ID/sutaba-server:$BRANCH_NAME',
    ]
images:
  - 'asia.gcr.io/$PROJECT_ID/sutaba-server'