variables:
  go-modules-volume: &go-modules-volume
    name: go-modules
    path: /go
  gopath: &gopath 'GOPATH=/go'
  enable_gomodule: &enable_gomodule 'GO111MODULE=on'
  go-mod-download-id: &go-mod-download-id 'go-mod-download'
  install-build-essential-id: &install-build-essential 'install-build-essential'
steps:
  - name: 'gcr.io/cloud-builders/go:debian'
    id: *install-build-essential
    env: ['GO111MODULE=on', 'GOPATH=/go']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y build-essential && cp /usr/bin/make ./
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/go'
    id: *go-mod-download-id
    env: [*enable_gomodule, *gopath]
    args: ['mod', 'download']
    waitFor: ['-']
    volumes: [*go-modules-volume]
  - name: 'gcr.io/cloud-builders/go:debian'
    env: [*enable_gomodule, *gopath]
    entrypoint: './make'
    args: ['lint']
    waitFor: [*go-mod-download-id, *install-build-essential]
    volumes: [*go-modules-volume]
  - name: 'gcr.io/cloud-builders/go:debian'
    env: [*enable_gomodule, *gopath]
    entrypoint: './make'
    args: ['lint']
    waitFor: [*go-mod-download-id, *install-build-essential]
    volumes: [*go-modules-volume]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-pull'
    entrypoint: 'bash'
    waitFor: ['-']
    args:
      - '-c'
      - |
        docker pull asia.gcr.io/$PROJECT_ID/sutaba-server:master || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['docker-pull']
    args: [ 'build',
            '-t', 'asia.gcr.io/$PROJECT_ID/sutaba-server:$BRANCH_NAME', '.',
            '--cache-from', 'asia.gcr.io/$PROJECT_ID/sutaba-server:master',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/sutaba-server:$BRANCH_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ $BRANCH_NAME = "master" ]; then
          gcloud beta run deploy sutaba-staging-server \
          --image asia.gcr.io/sutaba/sutaba-server:master \
          --platform managed \
          --update-env-vars CLASSIFIER_SERVER_HOST=https://classifier-server-lkui2qyzba-an.a.run.app
        fi
