ErrorTweetMessage: "@mpppk サーバ側でエラー発生したからなんとかして"
SorryTweetMessage: "sorry!!"
TweetKeyword: "スタバなう"
OwnerTwitterUserID: 1354555700
BotTwitterUserID: 1162195935398547457
ClassifierServerHost: "https://sutaba-lkui2qyzba-an.a.run.app"