version: "3.7"
services:
  web:
    build: .
    ports:
      - "1323:5000"
    environment:
      PORT: 5000
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      OWNER_TWITTER_ACCESS_TOKEN: ${OWNER_TWITTER_ACCESS_TOKEN}
      OWNER_TWITTER_ACCESS_TOKEN_SECRET: ${OWNER_TWITTER_ACCESS_TOKEN_SECRET}
      BOT_TWITTER_ACCESS_TOKEN: ${BOT_TWITTER_ACCESS_TOKEN}
      BOT_TWITTER_ACCESS_TOKEN_SECRET: ${BOT_TWITTER_ACCESS_TOKEN_SECRET}
  web-from-cr:
    image: asia.gcr.io/sutaba/sutaba-server
    ports:
      - "1323:5000"
    environment:
      PORT: 5000
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      OWNER_TWITTER_ACCESS_TOKEN: ${OWNER_TWITTER_ACCESS_TOKEN}
      OWNER_TWITTER_ACCESS_TOKEN_SECRET: ${OWNER_TWITTER_ACCESS_TOKEN_SECRET}
      BOT_TWITTER_ACCESS_TOKEN: ${BOT_TWITTER_ACCESS_TOKEN}
      BOT_TWITTER_ACCESS_TOKEN_SECRET: ${BOT_TWITTER_ACCESS_TOKEN_SECRET}
