version: "3.7"
services:
  web:
    build: .
    ports:
      - "1323:5000"
    environment:
      PORT: 5000
      CLASSIFIER_SERVER_HOST: https://classifier-server-lkui2qyzba-an.a.run.app
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      BOT_TWITTER_ACCESS_TOKEN: ${BOT_TWITTER_ACCESS_TOKEN}
      BOT_TWITTER_ACCESS_TOKEN_SECRET: ${BOT_TWITTER_ACCESS_TOKEN_SECRET}
      BOT_TWITTER_USER_ID: 1166922179323158528
      BOT_TWITTER_USER_SCREEN_NAME: sutaba_police2
  web-from-cr-master:
    image: asia.gcr.io/sutaba/sutaba-server:master
    ports:
      - "1323:5000"
    environment:
      PORT: 5000
      CLASSIFIER_SERVER_HOST: https://classifier-server-lkui2qyzba-an.a.run.app
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      BOT_TWITTER_ACCESS_TOKEN: ${BOT_TWITTER_ACCESS_TOKEN}
      BOT_TWITTER_ACCESS_TOKEN_SECRET: ${BOT_TWITTER_ACCESS_TOKEN_SECRET}
      BOT_TWITTER_USER_ID: 1166922179323158528
      BOT_TWITTER_USER_SCREEN_NAME: sutaba_police2
